# Generated by Django 5.2.17 on 2026-08-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_customization_images',
            field=models.PositiveIntegerField(default=0, help_text='Maximum number of reference images a customer can upload when customizing THIS product. Leave as 0 to use the site-wide default set in Site Settings.'),
        ),
    ]
