# Generated by Django 5.2.17 on 2026-08-21 05:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_colour_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expected_delivery_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of days after the order date this product is expected to be delivered. Leave as 0 to use the site-wide default set in Site Settings.'),
        ),
        migrations.AddField(
            model_name='product',
            name='inside_kerala_delivery_additional_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra delivery charge per additional quantity step, inside Kerala.', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='inside_kerala_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base delivery charge for this product when the delivery address is in Kerala.', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='inside_kerala_delivery_qty_step',
            field=models.PositiveIntegerField(default=1, help_text='Apply the additional Kerala delivery charge every this-many extra items.'),
        ),
        migrations.AddField(
            model_name='product',
            name='outside_kerala_delivery_additional_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra delivery charge per additional quantity step, outside Kerala.', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='outside_kerala_delivery_charge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base delivery charge for this product when the delivery address is outside Kerala.', max_digits=8),
        ),
        migrations.AddField(
            model_name='product',
            name='outside_kerala_delivery_qty_step',
            field=models.PositiveIntegerField(default=1, help_text='Apply the additional outside-Kerala delivery charge every this-many extra items.'),
        ),
    ]
