# Generated by Django 5.2.17 on 2026-08-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_expected_delivery_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_pricing_mode',
            field=models.CharField(choices=[('site_default', 'Use Site-wide Delivery Setting'), ('product', "Product Based (this product's own fixed fee below)"), ('count', 'Count Based (tiered by how many of this product are ordered — Delivery → Count Rules)')], default='site_default', help_text="Decided here, when the product is added: how THIS product's delivery is charged. 'Product Based' always uses this product's own First/Additional Item Delivery Charge below, regardless of the site-wide delivery mode. 'Count Based' always uses the site's Product Count delivery rules (Site Settings → Delivery → Count Rules), tiered by this product's own ordered quantity. Leave as 'Use Site-wide Delivery Setting' to follow whatever delivery mode Site Settings → Delivery is currently set to.", max_length=20),
        ),
    ]
