# Generated by Django 5.2.17 on 2026-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_delivery_pricing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='preview_area_points',
            field=models.JSONField(blank=True, default=list, help_text="Polygon points (list of [x_percent, y_percent], 0-100, relative to this colour's primary image) marking where a customer's uploaded customization photo should be shown as a live preview. Set from Admin → Products → Colour Variants → 'Set preview area'. Empty means no live preview is shown for this colour."),
        ),
    ]
