# Generated by Django 5.2.17 on 2026-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productvariant_preview_area_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previewarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
