# Generated by Django 5.2.10 on 2026-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_gateway_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stock_reduced',
            field=models.BooleanField(default=False),
        ),
    ]
