# Generated by Django 5.2.10 on 2026-07-20 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_stock_reduced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stock_reduced',
            new_name='stock_processed',
        ),
    ]
