# Generated by Django 5.2.10 on 2026-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_stock_reduced_payment_stock_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Digital Galleria', max_length=150)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(upload_to='payment_qr/')),
                ('instructions', models.TextField(blank=True, default='Scan or download the QR code and manually enter the exact order amount shown on the payment page.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UPI Payment Setting',
                'verbose_name_plural': 'UPI Payment Settings',
            },
        ),
    ]
