# Generated by Django 4.2.7 on 2026-07-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_screenshot',
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='upi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='UPI Transaction ID / UTR'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(blank=True, default='Pay the exact order amount using the UPI ID shown above. After completing the payment, enter the UTR / Transaction Reference Number below for verification.'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
