# Generated by Django 4.2.7 on 2026-07-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='upi_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='UPI Transaction ID / UTR'),
        ),
    ]
