# Generated by Django 4.2.7 on 2026-07-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_payment_upi_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verification Pending', 'Verification Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected'), ('Failed', 'Failed')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(blank=True, default='Pay the exact order amount shown on this page. Enter the amount manually in your UPI app. After completing the payment, enter the UTR / Transaction Reference Number and submit it for verification.'),
        ),
    ]
