# Generated by Django 4.2.7 on 2026-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsettings',
            name='business_name',
        ),
        migrations.AddField(
            model_name='paymentsettings',
            name='upi_receiver_name',
            field=models.CharField(blank=True, default='', help_text='Enter the receiver/payee name associated with the configured UPI ID.', max_length=150, verbose_name='UPI Receiver Name'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='instructions',
            field=models.TextField(blank=True, default='Tap Open UPI App and verify the receiver details and exact payment amount before paying. The exact order amount should be automatically passed to supported UPI apps. If your UPI app does not automatically show the amount, manually enter the exact amount displayed on this payment page. After completing the payment, return to this page and enter the UTR / Transaction Reference Number for verification.', verbose_name='Payment Instructions'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Optional. Upload the QR code used to receive UPI payments.', null=True, upload_to='payment_qr/', verbose_name='UPI QR Code'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='upi_id',
            field=models.CharField(blank=True, help_text='Enter the UPI ID that should receive customer payments.', max_length=100, verbose_name='UPI ID'),
        ),
    ]
