<<<<<<< HEAD
# Generated by Django 6.0.7 on 2026-08-03 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.2.7 on 2026-07-24 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> d386a61523ce78cb8e24f09895792e16b0693321


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('store', '0005_alter_review_product_alter_review_rating'),
=======
        ('products', '0003_product_customization_upload_mode_and_more'),
>>>>>>> d386a61523ce78cb8e24f09895792e16b0693321
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('upi_id', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(upload_to='payment_qr/')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_photo', models.ImageField(upload_to='customer_uploads/')),
                ('custom_text', models.CharField(blank=True, max_length=200)),
                ('font_name', models.CharField(default='Poppins', max_length=100)),
                ('frame_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=2)),
                ('frame_color', models.CharField(default='Black', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
=======
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='customizations/originals/')),
                ('customization_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_customizations', to='products.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomizationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customizations/images/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='customization.customization')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
>>>>>>> d386a61523ce78cb8e24f09895792e16b0693321
        ),
    ]
