# Generated by Django 6.0.7 on 2026-08-06 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
        ('orders', '0002_order_payment_method_order_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customizations', to='orders.order'),
        ),
    ]
