# Generated by Django 6.1 on 2026-08-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_count_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method_snapshot',
            field=models.CharField(blank=True, choices=[('weight', 'Weight Based'), ('count', 'Product Count Based')], help_text='Delivery calculation method active when this order was placed.', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_quantity_snapshot',
            field=models.PositiveIntegerField(default=0, help_text='Total product quantity in the cart when this order was placed (count mode).'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_rule_label_snapshot',
            field=models.CharField(blank=True, help_text='Human-readable description of the delivery rule/slab that was applied.', max_length=120),
        ),
        migrations.AlterField(
            model_name='deliverycountrule',
            name='max_items',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for an open-ended rule.', null=True),
        ),
    ]
