# Generated by Django 5.2.17 on 2026-08-19 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_method_snapshot_and_more'),
        ('products', '0004_colour_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='order',
            name='checkout_token',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colour_hex_snapshot',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='colour_name_snapshot',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sku_snapshot',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant'),
        ),
    ]
