# Generated by Django 5.2.17 on 2026-08-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_options_order_checkout_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, help_text="Stamped automatically the moment the order status first becomes 'Delivered'.", null=True),
        ),
    ]
