# Generated by Django 5.2.17 on 2026-08-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('verified', 'Verified'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
    ]
