# Generated by Django 5.2.17 on 2026-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_is_buy_now_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_state_snapshot',
            field=models.CharField(blank=True, help_text='Delivery address state used for Kerala/outside-Kerala delivery pricing.', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method_snapshot',
            field=models.CharField(blank=True, choices=[('weight', 'Weight Based'), ('count', 'Product Count Based'), ('product_state', 'Per-Product (Kerala / Outside Kerala)')], help_text='Delivery calculation method active when this order was placed.', max_length=13),
        ),
    ]
