# Generated by Django 5.2.17 on 2026-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_delivery_state_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_deducted',
            field=models.BooleanField(default=False, help_text="Whether product/variant stock has been decremented for this order yet. Stock is only deducted once the order reaches 'Processing' (or later) — not at order placement/payment time — and is restored automatically if a processed order is later cancelled."),
        ),
    ]
