# Generated by Django 5.2.17 on 2026-08-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_whatsapp_chat_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='next_order_sequence',
            field=models.PositiveIntegerField(default=1000, help_text='The number the NEXT order will use, e.g. set 3002 to make the next order DG3002 — after that it counts up automatically (DG3003, DG3004, ...). Only change this if you need to reset or jump the numbering; leave it alone otherwise.'),
        ),
    ]
