# Generated by Django 5.2.17 on 2026-08-21 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_next_order_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='redirect_label',
            field=models.CharField(blank=True, default='', help_text="Button text for the redirect link, e.g. 'View Offers'. Defaults to 'Learn more' if left blank.", max_length=60),
        ),
        migrations.AddField(
            model_name='faq',
            name='redirect_link',
            field=models.URLField(blank=True, help_text='Optional destination URL. If set, the chatbot shows a button linking here when this FAQ matches.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_expected_delivery_days',
            field=models.PositiveIntegerField(default=5, help_text="Used for any product that doesn't have its own 'Expected Delivery Days' set."),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='delivery_mode',
            field=models.CharField(choices=[('weight', 'Weight Based'), ('count', 'Product Count Based'), ('product_state', 'Per-Product (Kerala / Outside Kerala)')], default='weight', max_length=13),
        ),
    ]
