# Generated by Django 5.2.17 on 2026-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Digital Galleria', max_length=100)),
                ('tagline', models.CharField(default='Memories. Made Personal.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('whatsapp_url', models.CharField(blank=True, help_text='e.g. https://wa.me/91XXXXXXXXXX', max_length=255)),
                ('instagram_url', models.CharField(blank=True, max_length=255)),
                ('facebook_url', models.CharField(blank=True, max_length=255)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('payment_instructions', models.TextField(blank=True, default='Scan the QR code or pay to the UPI ID above, then upload your payment screenshot.')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('footer_text', models.CharField(default='With love, Team Digital Galleria.', max_length=255)),
                ('about_heading', models.CharField(blank=True, default='About Digital Galleria', max_length=200)),
                ('about_description', models.TextField(blank=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_mission', models.TextField(blank=True)),
                ('about_values', models.TextField(blank=True)),
                ('hero_heading', models.CharField(blank=True, default='Moments. Made personal.', max_length=200)),
                ('hero_subheading', models.TextField(blank=True, default='Premium frames, gifts and keepsakes crafted around your favourite people and memories.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('hero_button_text', models.CharField(blank=True, default='Explore Collection', max_length=50)),
                ('hero_button_url', models.CharField(blank=True, default='/products/', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='StorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='story/')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=4)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
