# Generated by Django 5.2.17 on 2026-08-13 08:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('category', models.CharField(choices=[('materials', 'Materials'), ('packaging', 'Packaging'), ('shipping', 'Shipping'), ('marketing', 'Marketing'), ('salary', 'Salary'), ('rent', 'Rent'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
