# Generated by Django 5.2.17 on 2026-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('discount_text', models.CharField(help_text='e.g. "10% OFF"', max_length=50)),
                ('cta_text', models.CharField(default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('target_gender', models.CharField(choices=[('all', 'Everyone'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=10)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
