# Generated by Django 5.2.17 on 2026-08-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ads/')),
                ('description', models.TextField(blank=True)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_section', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('product_section', 'Product Section'), ('offer_section', 'Offer Section'), ('between_products', 'Between Product Cards'), ('promotional_strip', 'Promotional Strip')], default='homepage_banner', max_length=32)),
                ('target_gender', models.CharField(choices=[('all', 'Everyone'), ('male', 'Male'), ('female', 'Female')], default='all', max_length=10)),
                ('full_screen_popup', models.BooleanField(default=False, help_text='Only enable for special campaigns')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
