# Generated by Django 5.2.17 on 2026-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0002_multiple_images_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizationimage',
            name='preview_offset_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationimage',
            name='preview_offset_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customizationimage',
            name='preview_scale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
