# Generated by Django 4.2.7 on 2026-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Internal/admin title for the advertisement.', max_length=200)),
                ('ad_type', models.CharField(choices=[('text', 'Text Advertisement'), ('image', 'Image Advertisement')], default='text', help_text='Choose whether this advertisement is a scrolling text ad or popup image ad.', max_length=10)),
                ('text', models.TextField(blank=True, help_text='Text displayed as a scrolling advertisement from right to left.')),
                ('image', models.ImageField(blank=True, help_text='Upload an image only for Image Advertisement.', null=True, upload_to='advertisements/')),
                ('link', models.URLField(blank=True, help_text='Optional destination URL when the ad is clicked.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active advertisements will appear on the website.')),
                ('start_at', models.DateTimeField(blank=True, help_text='Optional. Advertisement will not appear before this date/time.', null=True)),
                ('end_at', models.DateTimeField(blank=True, help_text='Optional. Advertisement will stop appearing after this date/time.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
