# Generated by Django 4.2.7 on 2026-07-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('text', 'Text Advertisement'), ('image', 'Image Advertisement')], db_index=True, default='text', help_text='Choose Text Advertisement or Image Advertisement.', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='end_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional. Leave blank if the advertisement should remain active until manually disabled.', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, help_text='Required only for Image Advertisement.', null=True, upload_to='advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Turn this ON to allow the advertisement to appear.'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Optional link opened when the advertisement is clicked.'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='start_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Optional. Leave blank to start immediately.', null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Required only for Text Advertisement. This text will scroll from right to left on the homepage.'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Internal title used to identify this advertisement.', max_length=200),
        ),
    ]
