# Generated by Django 4.2.7 on 2026-07-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_aboutsection_socialmedialink'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Enable this to allow customers to send customization photos through WhatsApp.')),
                ('whatsapp_chat_link', models.URLField(blank=True, default='', help_text='Paste the full WhatsApp direct chat link. Customers will be sent directly to this chat.', max_length=500)),
                ('whatsapp_title', models.CharField(blank=True, default='Send Photos via WhatsApp', max_length=150)),
                ('whatsapp_instructions', models.TextField(blank=True, default='Send all customization photos through WhatsApp. After sending the photos, return to this page and confirm that you have sent them.')),
                ('website_upload_title', models.CharField(blank=True, default='Upload Photos Here', max_length=150)),
                ('website_upload_description', models.TextField(blank=True, default='Upload your customization photos directly from your device.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customization Setting',
                'verbose_name_plural': 'Customization Settings',
            },
        ),
    ]
