"""
<<<<<<< HEAD
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%)c9+d0(np(or__nesp%*8@!j%h8^g(x&7q@ftej0+8&e=3_aq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
    'cart',
    'accounts',
    'orders',
    'wishlist',
    'customization',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

SECRET_KEY = os.getenv("SECRET_KEY")

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
=======
Django settings for Digital Galleria
Production / Render ready configuration
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")
# =========================================================
# BASE DIRECTORY
# =========================================================



# =========================================================
# SECURITY
# =========================================================

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-development-key"
)

DEBUG = os.environ.get(
    "DEBUG",
    "True"
).lower() == "true"


# =========================================================
# ALLOWED HOSTS
#
# Render hostname is automatically available through
# RENDER_EXTERNAL_HOSTNAME.
# =========================================================

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "*"
]


RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    "RENDER_EXTERNAL_HOSTNAME"
)

if RENDER_EXTERNAL_HOSTNAME:

    ALLOWED_HOSTS.append(
        RENDER_EXTERNAL_HOSTNAME
    )


# Optional manual hosts from environment:
#
# ALLOWED_HOSTS=example.com,www.example.com

EXTRA_ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    ""
)

if EXTRA_ALLOWED_HOSTS:

    ALLOWED_HOSTS.extend(

        host.strip()

        for host in
        EXTRA_ALLOWED_HOSTS.split(",")

        if host.strip()

    )


# =========================================================
# CSRF TRUSTED ORIGINS
# =========================================================

CSRF_TRUSTED_ORIGINS = []


if RENDER_EXTERNAL_HOSTNAME:

    CSRF_TRUSTED_ORIGINS.append(

        f"https://{RENDER_EXTERNAL_HOSTNAME}"

    )


EXTRA_CSRF_ORIGINS = os.environ.get(
    "CSRF_TRUSTED_ORIGINS",
    ""
)

if EXTRA_CSRF_ORIGINS:

    CSRF_TRUSTED_ORIGINS.extend(

        origin.strip()

        for origin in
        EXTRA_CSRF_ORIGINS.split(",")

        if origin.strip()

    )


# =========================================================
# INSTALLED APPLICATIONS
# =========================================================

INSTALLED_APPS = [

    # Django

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",


    # Third Party

    "rest_framework",
    "corsheaders",


    # Local Apps

    "accounts",
    "products",
    "categories",
    "customization",
    "cart",
    "orders.apps.OrdersConfig",
    "payments",
    "coupons",
    "homepage",

]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    # Security

    "django.middleware.security.SecurityMiddleware",


    # WhiteNoise
    #
    # Must be directly after SecurityMiddleware.

    "whitenoise.middleware.WhiteNoiseMiddleware",


    # CORS

    "corsheaders.middleware.CorsMiddleware",


    # Django middleware

    "django.contrib.sessions.middleware.SessionMiddleware",

    "django.middleware.common.CommonMiddleware",

    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",

    "django.middleware.clickjacking.XFrameOptionsMiddleware",

]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = "config.urls"


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {

        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [

            BASE_DIR / "templates",

        ],

        "APP_DIRS":
            True,

        "OPTIONS": {

            "context_processors": [

                "django.template.context_processors.request",

                "django.contrib.auth.context_processors.auth",

                "django.contrib.messages.context_processors.messages",

            ],

        },

    },

]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = "config.wsgi.application"


# =========================================================
# DATABASE
#
# Currently SQLite.
#
# This works locally.
#
# IMPORTANT:
# For production on Render we will configure persistent
# PostgreSQL in the next deployment step.
# =========================================================
# =========================================================
# DATABASE
#
# LOCAL DEVELOPMENT:
#   SQLite
#
# RENDER PRODUCTION:
#   Supabase PostgreSQL through DATABASE_URL
#
# Render Environment:
#
# DATABASE_URL =
# Supabase Session Pooler connection URI
#
# =========================================================

DATABASE_URL = os.environ.get(
    "DATABASE_URL"
)


if DATABASE_URL:

    # =====================================================
    # PRODUCTION / RENDER
    # =====================================================

    DATABASES = {

        "default":

            dj_database_url.parse(

                DATABASE_URL,

                conn_max_age=600,

                conn_health_checks=True,

            )

    }

else:

    # =====================================================
    # LOCAL DEVELOPMENT
    # =====================================================

    DATABASES = {

        "default": {

            "ENGINE":
                "django.db.backends.sqlite3",

            "NAME":
                BASE_DIR / "db.sqlite3",

            "OPTIONS": {

                "timeout": 30,

            },

            "CONN_MAX_AGE": 0,

        }

    }
# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = []


# =========================================================
# DJANGO REST FRAMEWORK
# =========================================================

REST_FRAMEWORK = {

    "DEFAULT_PERMISSION_CLASSES": [

        "rest_framework.permissions.AllowAny",

    ],

}


# =========================================================
# CORS
# =========================================================

CORS_ALLOWED_ORIGINS = [

    "http://localhost:5173",

]


CORS_ALLOW_CREDENTIALS = True


# =========================================================
# LANGUAGE / TIMEZONE
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"
>>>>>>> d386a61523ce78cb8e24f09895792e16b0693321

USE_I18N = True

USE_TZ = True


<<<<<<< HEAD
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
=======
# =========================================================
# STATIC FILES
#
# IMPORTANT:
#
# static/
#     = Our source files
#
# staticfiles/
#     = collectstatic output
#
# Never use the same directory for both.
# =========================================================

STATIC_URL = "/static/"


# Our manually created static directory:
#
# static/
#   gifs/
#       order-success.gif
#
#   sounds/
#       order-success.mp3

STATICFILES_DIRS = [

    BASE_DIR / "static",

]


# Production collectstatic destination

STATIC_ROOT = (

    BASE_DIR

    /

    "staticfiles"

)


# =========================================================
# STATIC STORAGE
#
# WhiteNoise serves static files in production.
# =========================================================
STORAGES = {

    # =====================================================
    # MEDIA / UPLOADED FILES
    #
    # Product images
    # Product gallery images
    # Customization images
    # Profile images
    # Advertisements
    # Payment QR images
    # etc.
    #
    # These will be stored in Supabase Storage.
    # =====================================================

    "default": {

        "BACKEND":
            "config.supabase_storage.SupabaseStorage",

    },



    # =====================================================
    # STATIC FILES
    #
    # CSS / JS / GIF / static images etc.
    # WhiteNoise continues to handle these.
    # =====================================================

    "staticfiles": {

        "BACKEND":
            "whitenoise.storage.CompressedManifestStaticFilesStorage",

    },

}

# =========================================================
# MEDIA FILES
#
# Temporary local configuration.
#
# IMPORTANT:
#
# Customer uploads such as:
#
# - customization originals
# - customization previews
# - product images
# - profile images
# - payment QR
# - advertisements
#
# should use persistent cloud storage before final
# production deployment.
# =========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = (

    BASE_DIR

    /

    "media"

)


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = (

    "django.db.models.BigAutoField"

)


# =========================================================
# CUSTOM USER MODEL
# =========================================================

AUTH_USER_MODEL = "accounts.User"


# =========================================================
# PRODUCTION SECURITY
#
# These automatically activate when DEBUG=False.
# =========================================================

if not DEBUG:

    SECURE_PROXY_SSL_HEADER = (

        "HTTP_X_FORWARDED_PROTO",

        "https"

    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True
>>>>>>> d386a61523ce78cb8e24f09895792e16b0693321
