# Generated by Django 5.2.17 on 2026-08-18 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage_attachments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-created_date']},
        ),
    ]
