# Generated by Django 5.2.10 on 2026-07-20 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_product_alter_orderitem_quantity_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcustomization',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='productcustomization',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.productcustomization'),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_customizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
