# Generated by Django 4.2.7 on 2026-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancellation_requested_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='stock_restored',
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_admin_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_status',
            field=models.CharField(choices=[('None', 'None'), ('Requested', 'Requested'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Not Required', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_before_cancellation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restored',
            field=models.BooleanField(default=False),
        ),
    ]
