# Generated by Django 4.2.7 on 2026-07-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_coupon_code_order_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomizationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='customizations/multiple/')),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to='orders.productcustomization')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
