# Generated by Django 4.2.7 on 2026-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productcustomizationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Rejected', 'Rejected'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
