# Generated by Django 4.2.7 on 2026-07-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomization',
            name='submission_method',
            field=models.CharField(choices=[('website', 'Website Upload'), ('whatsapp', 'WhatsApp')], db_index=True, default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='productcustomization',
            name='whatsapp_photos_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcustomization',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='customizations/originals/'),
        ),
    ]
