# Generated by Django 5.2.17 on 2026-08-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('coupons', '0002_initial'),
        ('products', '0004_colour_productvariant_variantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='restricted_coupons', to='categories.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='restricted_coupons', to='products.product'),
        ),
    ]
