# Generated by Django 4.2.7 on 2026-07-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_height',
            field=models.FloatField(default=50, help_text='Height of the printable/customizable area as a percentage of the product image.'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_width',
            field=models.FloatField(default=50, help_text='Width of the printable/customizable area as a percentage of the product image.'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_x',
            field=models.FloatField(default=25, help_text='Print area horizontal starting position. Enter a percentage from 0 to 100.'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_y',
            field=models.FloatField(default=25, help_text='Print area vertical starting position. Enter a percentage from 0 to 100.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=True, help_text='Enable this option if customers are allowed to customize this product.'),
        ),
    ]
