# Generated by Django 4.2.7 on 2026-07-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_customization_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customization_upload_mode',
            field=models.CharField(choices=[('single', 'Single Image'), ('multiple', 'Multiple Images')], default='single', help_text='Choose Multiple Images for products such as Polaroids where customers may upload many photos.', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='image_limit_based_on_quantity',
            field=models.BooleanField(default=True, help_text='If enabled, the maximum number of customer images equals the selected product quantity.'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_customization_images',
            field=models.PositiveIntegerField(default=1, help_text='Maximum customer images when the image limit is not based on product quantity.'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_order_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Maximum quantity allowed in one order. Enter 0 to use available stock as the limit.'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Minimum quantity a customer must order.'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.product')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
