# Generated by Django 4.2.7 on 2026-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_customization_upload_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery charge for this product. Enter 0 for free delivery.', max_digits=10, verbose_name='Delivery Charge'),
        ),
    ]
